---

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - '*.*'
      - '*.*.*'
  pull_request: null

name: MySQL

jobs:
  phpunit:
    uses: cycle/gh-actions/.github/workflows/db-mysql.yml@master

...
